### ISSUE TITLE
publish on nixpkgs

### ISSUE THREAD

**Issue by phanirithvij** [vimpostor/blobdrop#11]
Requesting to publish the next release on nixpkgs.

**Comment by vimpostor** [comment]
I am all for it, but wouldn't this issue be more appropriate at nixpkgs?
Usually I don't like sending in packaging requests for software I write myself, as that feels a little like self-promotion. That's why I opted for a flake.nix instead of a package in nixpkgs, but perhaps it is a bit different now given that this project has gathered a few Github stars in the meantime.

**Comment by phanirithvij** [comment]
https://github.com/NixOS/nixpkgs/issues/346429
